### ISSUE TITLE
some new firmware found in latest Fritzbox production images

### ISSUE THREAD

**Issue by geos-github** [xdarklight/lantiq-xdsl-firmware-info#20] opened 2019-12-20 23:37 UTC
FRITZ.Box_7490-07.12.image (29-07-2019) contains 5.9.1.4.0.7
FRITZ.Box_7412-06.86.image (30-09-2019) contains 5.9.0.12.1.7

(version numbers refer to Annex B firmware; Annex A should be available in the Fritzbox firmwares, too, as a binary patch)

Both firmwares connect with profile 17a, G.993.5 (VDSL2 with down- and upstream vectoring).
I didn't try them too extensively yet, though.

**Comment by xdarklight** [comment] 2020-02-27 21:05
duplicate of #19

**Closed by xdarklight** 2020-02-27 21:05 UTC
